language: php

sudo: false

dist: trusty

git:
  depth: 5
    
cache:
  - composer
  - $HOME/.composer/cache
  
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true
  include:
    - php: hhvm
      env: HHVM=1
  allow_failures:
    - php: nightly

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." && -z "$HHVM" ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - composer self-update
  - composer install

script:
  - composer test