language: php

sudo: false

dist: trusty

git:
  depth: 5
  
php:
  - hhvm
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install

script:
  - composer test